[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
reqwest = { version = "0.11", features = ["multipart", "json", "rustls-tls"] }
chrono = "0.4"
ethers = { version = "1.0.2", features = ["abigen"] }
sha2 = "0.10"
